Feature/wallet-addresses-widget
TokelPlatform/tokel_dapp pull request #271
Opened 2022-04-02 18:15 UTC by rannyeribaptist

HI there 👋

This is my first PR for Tokel Project and I updated a few things in the Dashboard:

The history widget is moved up, replacing the graphs widget. I also added shortcuts in the list as suggested by [piggydoughnut](https://github.com/piggydoughnut), so you can copy the **Tx id** and open the transaction in the browser straight from the list:

![image](https://user-images.githubusercontent.com/14826006/161393186-995f8387-31d0-45bf-9c88-469a057f6dc4.png)

We have a new widget now! The Wallet Addresses widget displays your **account's address** and **pubkey**:

![image](https://user-images.githubusercontent.com/14826006/161393238-96230f91-8783-4e3e-bc41-82f01078cb6f.png)

The entire Dashboard now looks like this:

![image](https://user-images.githubusercontent.com/14826006/161393256-d25098bf-d574-4b68-b548-3923d5988ac2.png)

2022-04-03 19:56 UTC, lenilsonjr reviewed
looking good! left some notes

2022-04-03 19:56 UTC, lenilsonjr commented on src/components/Dashboard/widgets/Embeds/ActivityListEmbed.tsx
> +            <ActivityListItem key={tx.txid + tx.received}>
we can swap this key to be just the txid

```suggestion
            <ActivityListItem key={tx.txid}>
```

2022-04-03 19:56 UTC, lenilsonjr commented on src/components/Dashboard/widgets/Embeds/WalletAddressesEmbed.tsx
> +  const isNFT = tokenInfo && tokenInfo.supply === 1;
feel free to use optional chaining here
```suggestion
  const isNFT = tokenInfo?.supply === 1;
```

2022-04-03 19:56 UTC, lenilsonjr commented on src/components/Dashboard/widgets/Embeds/WalletAddressesEmbed.tsx
> +const WalletAddresses = () => {
Mind changing this component name to match the filename?

2022-04-07 07:06 UTC, piggydoughnut commented
Looks good, agree with Lenni's remarks. Its a pass for me. @lenilsonjr said you will look at the tests together. So once the tests pass we can merge 👌🏼

2022-04-07 07:06 UTC, piggydoughnut commented
Looks good, agree with Lenni's remarks. Its a pass for me. @lenilsonjr said you will look at the tests together. So once the tests pass we can merge 👌🏼

2022-04-07 07:07 UTC, piggydoughnut requested changes
Please apply the changes Lenni suggested and make the tests pass so the CI is happy.

2022-04-11 22:35 UTC, lenilsonjr approved these changes
looks good. Since @piggydoughnut gave green light above, going to merge this one rn

2022-04-11 22:35 UTC, merged