Fixed TKL price in USD and polished it's styling
TokelPlatform/tokel_dapp pull request #278
Opened 2022-04-25 22:16 UTC by rannyeribaptist

Hello people 🤘

The Tokel USD price displayed in the dashboard is now fixed by switching from coinpaprika to nomics. I also improved its visuals a little bit to make it fit better with the rest of the dashboard 😄. The end result will be shown like this:

![image](https://user-images.githubusercontent.com/14826006/165183600-4c6e2a9a-8d41-4ee2-a8f0-22e3ad3c25bb.png)

Note: since we changed the source of the price information, I decided to keep the update period (the time it takes to update the information) the same as before, to see how it's going to behave. According to the documentation, the keys have a rate limit of one request per second (1rps), so we are still within the limits.

reference: https://nomics.com/docs#section/Rate-Limits

2022-04-25 22:21 UTC, lenilsonjr commented
Thanks for the PR 👋 

Couple general thoughts beforehand:

- I'll throw the nomics API & our API key behind a reverse-proxy and send you the URL so you can update the PR later
- Let's still adjust to load the price only ONCE when the dApp starts, no need to have a high refresh rate for now imo. Specially since the rate limit can be reached if say, multiple people are using the dApp at the same time and continuously requesting nomics with our API key.

I'll do a code review on this one as soon as I can.

2022-04-26 04:39 UTC, piggydoughnut commented on src/vars/defines.ts
> +export const TOKEL_PRICE_URL = `https://api.nomics.com/v1/currencies/ticker?key=${process.env.NOMICS_API_KEY}&ids=TKL2`;
Do we have a `.env` file now? Since we are using process.env.NOMICS_API_KEY ?
If yes please add a note about it in the README.

Not sure what Lenny means by `I'll throw the nomics API & our API key behind a reverse-proxy and send you the URL so you can update the PR later` I guess that is another option.

2022-04-26 04:40 UTC, piggydoughnut commented on src/vars/defines.ts
> +export const TOKEL_PRICE_URL = `https://api.nomics.com/v1/currencies/ticker?key=${process.env.NOMICS_API_KEY}&ids=TKL2`;
Oh also, definitely points for not exposing API_KEY in the code 👌🏼

2022-04-28 03:05 UTC, rannyeribaptist commented on src/vars/defines.ts
> +export const TOKEL_PRICE_URL = `https://api.nomics.com/v1/currencies/ticker?key=${process.env.NOMICS_API_KEY}&ids=TKL2`;
Hey @piggydoughnut, I just followed the other variables we have in other files in the app. I defined the value of that variable locally in my console, but if we're already using a different solution for the environment variables I can change that. Do you have specific instructions for that?

2022-04-28 11:35 UTC, lenilsonjr commented on src/vars/defines.ts
> +export const TOKEL_PRICE_URL = `https://api.nomics.com/v1/currencies/ticker?key=${process.env.NOMICS_API_KEY}&ids=TKL2`;
@rannyeribaptist I'm gonna (meaning, I've been trying lol) setup a reverse-proxy and we won't need to ship the dApp with an API key. It's not desirable I guess to ship a desktop app with an API key that can be exploited for other purposes other than fetching the price for TKL.

2022-05-02 14:32 UTC, lenilsonjr requested changes
@rannyeribaptist `http://price.tokel.io` is up, please replace the URL. also please make sure we only fire this request once when the dApp opens for the first time, for the time being 🙏

2022-05-05 22:40 UTC, lenilsonjr approved these changes
sweet PR, thank you!

2022-05-05 22:40 UTC, merged